using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Hui : MonoBehaviour
{   
    public bool GameEscape = false; //ว๖ภ็ escธฆ ดญทถดยม๖ ดฉธฃม๖ พสพาดยม๖ พหทมมึดย บฏผ๖
    public GameObject pauseMainCanvas; //ภฯฝรมคม๖ธฆ ดฉธฆ ฝร ณชฟภดย Ui
    public Button ResumeButton; //ภฬพ๎วฯฑโ น๖ฦฐ บฏผ๖
    public Button PauseButton; //ภฯฝรมคม๖ น๖ฦฐ บฏผ๖

    void Start()
    {
        PauseButton.onClick.AddListener(OnPauseButtonClicked);
        ResumeButton.onClick.AddListener(OnResumeButtonClicked);
    }
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape)) //escธฆ ดญทถภปถง
        {
            if(GameEscape) //ฐิภำภฬ ฝววเม฿ภฬธ้ ธุร฿ฐํ ธุรแป๓ลยธ้ ฝววเวฯฑโ
            {
                ResumeGame();
            }   
            else 
            {
                PauseGame();
            }
        }
    }
    void OnPauseButtonClicked() //ลฌธฏ ฝร ฐิภำ ภฯฝรมคม๖
    {
        if (!GameEscape)
        {
            PauseGame();
        }
    }

    void OnResumeButtonClicked() //ลฌธฏ ฝร ฐิภำ ภฯฝรมคม๖ วุมฆ
    {
        if (GameEscape)
        {
            ResumeGame();
        }
    }

    public void PauseGame() //ฐิภำ ภฯฝรมคม๖ วิผ๖
    {
        GameManager.Instance.Pause();
        GameEscape = true;
        pauseMainCanvas.SetActive(true);

        PauseButton.gameObject.SetActive(false);
        ResumeButton.gameObject.SetActive(true);
    }

    public void ResumeGame() //ฐิภำ ภฯฝรมคม๖ วุมฆ วิผ๖
    {
        GameManager.Instance.Resume();
        GameEscape = false;
        pauseMainCanvas.SetActive(false);

        ResumeButton.gameObject.SetActive(false);
        PauseButton.gameObject.SetActive(true);
    }
}
